services:
  - name: postgres
    type: postgres
    source:
      type: image
      image: postgres:16-alpine
    domains: []
    env:
      POSTGRES_DB: distribuidora_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    mounts:
      - type: volume
        name: postgres-data
        mountPath: /var/lib/postgresql/data

  - name: backend
    type: app
    source:
      type: github
      owner: elian-pro
      repo: testd
      branch: claude/install-easypanel-vps-B498l
      path: /backend
    build:
      type: dockerfile
      dockerfile: Dockerfile
    domains:
      - host: api.${DOMAIN}
    env:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: distribuidora_db
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    mounts:
      - type: volume
        name: backend-uploads
        mountPath: /app/uploads
    ports:
      - published: 3000
        target: 3000

  - name: frontend
    type: app
    source:
      type: github
      owner: elian-pro
      repo: testd
      branch: claude/install-easypanel-vps-B498l
      path: /frontend
    build:
      type: dockerfile
      dockerfile: Dockerfile
      buildArgs:
        - VITE_API_URL=https://api.${DOMAIN}/api
    domains:
      - host: ${DOMAIN}
    ports:
      - published: 80
        target: 80
